name: Trigger Jenkins

on:
  push:
    branches: main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins build
        run: |
          curl -X POST http://ip10-0-27-6-d33s7o9ntdlhbpdsdbrg-8080.direct.lab-boris.fr/job/iac-pipeline/build --user "token:11a1cc05c4050ec7e552b50c3d55094438" 
